### PR TITLE
Add Apple bullshits

### PR DESCRIPTION
**Pull request by narze**
As seen on apple.com

### CODE REVIEW

**Comment by mourner** [comment]
Hmm, "any/more *" seems to generic — might have too many false positives to add this.

**Comment by narze** [comment]
👌 I'll remove that and add more generic terms

**Comment by narze** [comment]
Another question, is it possible to make terms that replace partially.

eg.
`more power` -> `more bullshit` without replacing the `more` word

**Comment by mourner** [comment]
Looks excellent now! Regarding partial replacements — this has come up before, might be worth opening an issue to discuss.

**Pull request merged**
