### PR TITLE
Update terms.js

### PR DESCRIPTION
**Pull request by predmijat**

### CODE REVIEW

**Review by mourner — APPROVED** [review]
Wow, didn't know someone would use that word. Weird!

**Comment by predmijat** [comment]
https://oxide.computer/

Doesn't seem to work though!

**Comment by mourner** [comment]
@predmijat I didn't release the update yet, unless you tried with the version built from master?

**Comment by predmijat** [comment]
Yeah, in the meantime I checked how this actually works :)

**Pull request merged**
